[package]
name = "zone-edit"
version = "0.3.1"
description = "A minimal library of DNS provider utilities"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/tarka/zone-edit"
edition = "2024"

[dependencies]
async-lock = "3.4.1"
cfg-if = "1.0.3"
chrono = { version = "0.4.42", features = ["serde"], default-features = false }
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.7.0", default-features = false, features = ["client", "http1", "http2"] }
rustls = { version = "0.23.32", features = ["aws-lc-rs"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.16"
tracing = "0.1.41"
tracing-log = "0.2.0"
trait-variant = "0.1.2"
webpki-roots = "1.0.2"

# Smol support
futures-rustls = { version = "0.26.0", optional = true, features = ["aws-lc-rs"] }
smol = { version = "2.0.2", optional = true }
smol-hyper = { version = "0.1.1", optional = true }

# Tokio support
hyper-util = { version = "0.1.17", features = ["tokio"], optional = true }
tokio = { version = "1.47.1", features = ["rt", "test-util", "net", "full"], optional = true }
tokio-rustls = { version = "0.26.3", optional = true }

[features]
default = ["smol", "all-providers"]
all-providers = ["dnsmadeeasy", "gandi", "dnsimple"]
gandi = []
dnsimple = []
dnsmadeeasy = []
smol = ["dep:smol", "dep:smol-hyper", "dep:futures-rustls"]
tokio = ["dep:tokio", "dep:hyper-util", "dep:tokio-rustls"]

# Test features
# Disables http module tests that rely on external services
test_offline = []
test_gandi = ["gandi"]
test_dnsimple = ["dnsimple"]
test_dnsmadeeasy = ["dnsmadeeasy"]

[dev-dependencies]
acme-micro = "0.13.0"
anyhow = "1.0.100"
cfg-if = "1.0.3"
macro_rules_attribute = "0.2.2"
random-string = "1.1.0"
smol-macros = "0.1.1"
test-log = { version = "0.2.18", features = ["trace"] }
tracing-subscriber = "0.3.20"
tracing-test = "0.2.5"

[[example]]
name = "acme-dns01"
required-features = ["gandi"]

[lints.rust]
# FIXME: For early dev, remove before public release
dead_code = "allow"
