
name: Tests

on: [push]

jobs:

  test-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [smol, tokio]
        provider: [dnsimple, dnsmadeeasy]

    steps:
      
      - uses: actions/checkout@v4

      - name: Update Rust to latest
        run: rustup update

      - name: Run ${{ matrix.runtime }} tests
        env:
          DNSIMPLE_TEST_DOMAIN: ${{ secrets.DNSIMPLE_TEST_DOMAIN }}
          DNSIMPLE_TOKEN: ${{ secrets.DNSIMPLE_TOKEN }}
          DNSMADEEASY_TEST_DOMAIN: ${{ secrets.DNSMADEEASY_TEST_DOMAIN }}
          DNSMADEEASY_KEY: ${{ secrets.DNSMADEEASY_KEY }}
          DNSMADEEASY_SECRET: ${{ secrets.DNSMADEEASY_SECRET }}

        run: cargo test --features test_${{ matrix.runtime }},test_${{ matrix.provider }}
